[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NEXT_DISABLE_TURBOPACK = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
